import java.util.Random;

public class Deck{
   /* Card object array that represents the deck */
   private Card[] cards = new Card[52];
   
   /*Short Strings that represent the suits*/
   private final String C = "C";
   private final String H = "H";
   private final String D = "D";
   private final String S = "S";
   
   /*integer index that keeps track of the next card to draw*/
   private int deckPosition = 0;
   
   /*Constructor initializes all 52 Card in the deck array*/
   public Deck(){
      initializeDeck();
   }
   
   /*drawCard() returns the card on the top of the deck (starting at array index zero)*/
   public Card drawCard(){
      if(deckPosition == 52){
         shuffle();
      }
      deckPosition++;
      return cards[deckPosition-1];
   }
   
   /*shuffle() shuffles the deck by looping through the array and at each index
     swapping the card at that index with a card at another index 
     which is generated by a random number generator
   */
   public void shuffle(){
      Random rand = new Random();
      Card temp;
      int randomIndex = 0;
      for(int i = 0; i < cards.length; i++){
         randomIndex = rand.nextInt(52); //get random number 0 to 51
         temp = cards[i];
         cards[i] = cards[randomIndex];
         cards[randomIndex] = temp;
      }
      deckPosition = 0;
   }
   
   /*initializeDeck() initializes all the 52 cards in the deck array*/
   private void initializeDeck(){
      String url = "assets/images/cards/";
      String ext = ".png";
      
      /*2s*/
      cards[0] = new Card(url+ "2C" + ext, 2, C);
      cards[1] = new Card(url+ "2D" + ext, 2, D);
      cards[2] = new Card(url+ "2H" + ext, 2, H);
      cards[3] = new Card(url+ "2S" + ext, 2, S);
      
      /*3s*/
      cards[4] = new Card(url+ "3C" + ext, 3, C);
      cards[5] = new Card(url+ "3D" + ext, 3, D);
      cards[6] = new Card(url+ "3H" + ext, 3, H);
      cards[7] = new Card(url+ "3S" + ext, 3, S);
      
      /*4s*/
      cards[8] = new Card(url+ "4C" + ext, 4, C);
      cards[9] = new Card(url+ "4D" + ext, 4, D);
      cards[10] = new Card(url+ "4H" + ext, 4, H);
      cards[11] = new Card(url+ "4S" + ext, 4, S);
      
      /*5s*/
      cards[12] = new Card(url+ "5C" + ext, 5, C);
      cards[13] = new Card(url+ "5D" + ext, 5, D);
      cards[14] = new Card(url+ "5H" + ext, 5, H);
      cards[15] = new Card(url+ "5S" + ext, 5, S);
      
      /*6s*/
      cards[16] = new Card(url+ "6C" + ext, 6, C);
      cards[17] = new Card(url+ "6D" + ext, 6, D);
      cards[18] = new Card(url+ "6H" + ext, 6, H);
      cards[19] = new Card(url+ "6S" + ext, 6, S);
      
      /*7s*/
      cards[20] = new Card(url+ "7C" + ext, 7, C);
      cards[21] = new Card(url+ "7D" + ext, 7, D);
      cards[22] = new Card(url+ "7H" + ext, 7, H);
      cards[23] = new Card(url+ "7S" + ext, 7, S);
      
      /*8s*/
      cards[24] = new Card(url+ "8C" + ext, 8, C);
      cards[25] = new Card(url+ "8D" + ext, 8, D);
      cards[26] = new Card(url+ "8H" + ext, 8, H);
      cards[27] = new Card(url+ "8S" + ext, 8, S);
      
      /*9s*/
      cards[28] = new Card(url+ "9C" + ext, 9, C);
      cards[29] = new Card(url+ "9D" + ext, 9, D);
      cards[30] = new Card(url+ "9H" + ext, 9, H);
      cards[31] = new Card(url+ "9S" + ext, 9, S);
      
      /*10s*/
      cards[32] = new Card(url+ "10C" + ext, 10, C);
      cards[33] = new Card(url+ "10D" + ext, 10, D);
      cards[34] = new Card(url+ "10H" + ext, 10, H);
      cards[35] = new Card(url+ "10S" + ext, 10, S);
      
      /*Aces (start with default value 1, the possible 11 is calculated
        in game loop */
      cards[36] = new Card(url+ "AC" + ext, 1, C);
      cards[37] = new Card(url+ "AD" + ext, 1, D);
      cards[38] = new Card(url+ "AH" + ext, 1, H);
      cards[39] = new Card(url+ "AS" + ext, 1, S);
      
      /*Jacks*/
      cards[40] = new Card(url+ "JC" + ext, 10, C);
      cards[41] = new Card(url+ "JD" + ext, 10, D);
      cards[42] = new Card(url+ "JH" + ext, 10, H);
      cards[43] = new Card(url+ "JS" + ext, 10, S);
      
      /*Queens*/
      cards[44] = new Card(url+ "QC" + ext, 10, C);
      cards[45] = new Card(url+ "QD" + ext, 10, D);
      cards[46] = new Card(url+ "QH" + ext, 10, H);
      cards[47] = new Card(url+ "QS" + ext, 10, S);
      
      /*Kings*/
      cards[48] = new Card(url+ "KC" + ext, 10, C);
      cards[49] = new Card(url+ "KD" + ext, 10, D);
      cards[50] = new Card(url+ "KH" + ext, 10, H);
      cards[51] = new Card(url+ "KS" + ext, 10, S);   
   }

}